# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:


name: gefs_osn

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    container: rocker/geospatial:dev-osgeo
    steps:
      - uses: actions/checkout@v3

      - name: Install
        shell: Rscript {0}
        run: |
          remotes::install_deps(".", upgrade="never")
          remotes::install_github("eco4cast/vis4cast", upgrade="never")
          install.packages("bench")
          devtools::install()

      - name: Update GEFS
        shell: Rscript {0}
        run: |
          source("inst/cog-examples/gefs_cron.R")


