# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:


name: gefs_osn

jobs:
  docker:
    runs-on: [self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
#    container: rocker/geospatial
    steps:
      - uses: actions/checkout@v3

      - name: Install
        shell: Rscript {0}
        run: |
          devtools::install(dependencies=TRUE, upgrade="never")

      - name: Update GEFS
        shell: Rscript {0}
        run: |
          source("inst/cog-examples/gefs_cron.R")


